Security enhancement - digitally-signed the root file system image.
The public key used to verify the signature is inside the initramfs.

This is not enough, because it's possible to create a self-signed image and re-pack the initramfs with the new public key. Signing the kernel can be done through Secure Boot, but signing the initramfs requires some clever trick.

diff --git a/rules/initramfs/build b/rules/initramfs/build
--- a/rules/initramfs/build
+++ b/rules/initramfs/build
@@ -1,5 +1,5 @@
 PKG_DESC="The initial file system archive"
-PKG_DEPS="toybox sdaemons loksh lok luufs setfont tamsyn-font open-ath9k-htc-firmware"
+PKG_DEPS="toybox sdaemons loksh lok luufs setfont tamsyn-font ed25519 open-ath9k-htc-firmware"
 
 # files present in the initramfs
 INITRAMFS_FILES="bin/toybox
@@ -22,6 +22,7 @@ INITRAMFS_FILES="bin/toybox
                  bin/reboot
                  bin/setfont
                  bin/luufs
+                 bin/ed25519
                  share/consolefonts/Tamsyn8x16r.psf
                  lib/firmware/htc_7010.fw
                  lib/firmware/htc_9271.fw"
@@ -140,7 +141,8 @@ do
 		then
 			if [ -f /mnt/home/boot/bzImage ] &&
 			   [ -f /mnt/home/boot/initrd.xz ] &&
-			   [ -f /mnt/home/boot/rootfs.sfs ]
+			   [ -f /mnt/home/boot/rootfs.sfs ] &&
+			   [ -f /mnt/home/boot/rootfs.sig ]
 			then
 				is_found=1
 				break 2
@@ -151,6 +153,16 @@ do
 	sleep 1
 done
 if [ 0 -eq $is_found ]
+then
+	echo " failure."
+	exit
+fi
+
+# verify the root file system image signature
+echo -n " done.
+Verifying the root file system signature ..."
+ed25519 -c /mnt/home/boot/rootfs.sfs /mnt/home/boot/rootfs.sig /share/rootfs.pub
+if [ 0 -ne $? ]
 then
 	echo " failure."
 	exit
@@ -212,6 +224,9 @@ echo " done."
 exec chroot /mnt/union newpid rc
 fi' > "$initramfs_root/bin/rc"
 	chmod 755 "$initramfs_root/bin/rc"
+
+	cp /etc/packlad/pub_key "$initramfs_root/share/rootfs.pub"
+	chmod 644 "$initramfs_root/share/rootfs.pub"
 
 	# generate an initramfs archive
 	dir="$(pwd)"
